#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$env = (getenv('EXPEDIA_ENV') && !empty(getenv('EXPEDIA_ENV'))) ? strtolower(getenv('EXPEDIA_ENV')) : 'stag';
defined('YII_ENV') or define('YII_ENV', $env);

if (!in_array($env, ['dev','stag','prod']))
        die ('hmm, are you sure you\'re on the correct environment?, please consult with our tech monkies to get this solved');


// disable debugging on Production (prod)
if (in_array(YII_ENV, ['dev','stag']))
   defined('YII_DEBUG') or define('YII_DEBUG', true);
else
   defined('YII_DEBUG') or define('YII_DEBUG', false);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
